language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install gfortran

# command to install dependencies
install:
  - pip install .
  - pip install --allow-external=TA-Lib --allow-unverified=TA-Lib -r travis/requirements.txt

# command to run tests
# optimizer_testcase is ignored because it gets blocked in Travis.
# twitter_test is ignored because it requires credentials.
# talib_test is ignored until I get it to work on Travis.
# plotter_test is ignored until I get it to work on Travis.
script: nosetests --ignore-files=optimizer_testcase --ignore-files=twitter_test --ignore-files=talib_test  --ignore-files=plotter_test
