language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install ."
  - "pip install -r travis/requirements.txt"

# command to run tests
# optimizer_testcase is ignored because it gets blocked in Travis.
script: nosetests --ignore-files=optimizer_testcase
