application: pyalgotrade-optimizer
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /rw_common
  static_dir: resources/rw_common

- url: /strategy/.*
  script: pages/strategy.py
  login: admin

- url: /queue/seproducer
  script: queuehandlers/seproducer.py
  login: admin

- url: /queue/seconsumer
  script: queuehandlers/seconsumer.py
  login: admin

- url: /queue/seresult
  script: queuehandlers/seresult.py
  login: admin

- url: /.*
  script: pages/home.py
  login: admin

